# Generated by Django 5.1.1 on 2024-09-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_cart_tbl_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='quantity',
        ),
    ]
