# Generated by Django 5.1.1 on 2024-09-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_adders_tbl_register_adderss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_register',
            old_name='adderss',
            new_name='address',
        ),
    ]
