# Generated by Django 5.0.2 on 2025-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tbl_booktable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='tbl_slider',
            name='slider_picture',
            field=models.ImageField(null=True, upload_to='static/slider/'),
        ),
    ]
